#!name=个人广告过滤
#!desc=记录生活中遇到广告

[rewrite_local]
^https?:\/\/.*adInf.* url reject
^https?:\/\/.+\.hellobike\.com\/api\?query\.popup\.entrance url reject

[mitm]
hostname = weixinacc.qinlinyun.com, datagw-edge.alipay.com, guide-acs.m.taobao.com, bike.hellobike.com
