#!name=个人广告过滤
#!desc=记录生活中遇到广告
#!notes=清除牛皮癣，人人有责！

[MITM]
hostname = %APPEND%, weixinacc.qinlinyun.com

[Rule]
DOMAIN-SUFFIX,audid-api.taobao.com,REJECT
DOMAIN-SUFFIX,gw.alicdn.com,REJECT
DOMAIN-SUFFIX,alipayobjects.com,REJECT
DOMAIN-SUFFIX,datagw-edge.alipay.com,REJECT
DOMAIN-SUFFIX,mdap.alipay.com,REJECT
DOMAIN-SUFFIX,gw.alipayobjects.com,REJECT
DOMAIN-SUFFIX,cdn.ynuf.aliapp.org,REJECT
DOMAIN-SUFFIX,guide-acs.m.taobao.com,REJECT
DOMAIN-SUFFIX,amdc-thirdparty.alipay.com,REJECT
DOMAIN-SUFFIX,ilce.alicdn.com,REJECT
DOMAIN-SUFFIX,adgw.alipay.com,REJECT
DOMAIN-SUFFIX,g.cn.miaozhen.com,REJECT
DOMAIN-SUFFIX,guide-acs.m.taobao.com,REJECT
DOMAIN-SUFFIX,ksedt.com,REJECT
DOMAIN-SUFFIX,ctobsnssdk.com,REJECT
DOMAIN-SUFFIX,pangolin-sdk-toutiao1.com,REJECT
DOMAIN-SUFFIX,pangolin-sdk-toutiao1.com,REJECT
DOMAIN-SUFFIX,pangolin-sdk-toutiao.com,REJECT
DOMAIN-SUFFIX,kuaishou.com,REJECT
DOMAIN-SUFFIX,adukwai.com,REJECT
DOMAIN-SUFFIX,live.com,PROXY
DOMAIN-SUFFIX,mtyun.com,REJECT
DOMAIN-SUFFIX,maoyan.com,REJECT
DOMAIN-SUFFIX,dianping.com,REJECT
DOMAIN-SUFFIX,c-ztuni.tec73.com,REJECT
DOMAIN-SUFFIX,kuaishouzt.com,REJECT
DOMAIN-SUFFIX,dreport.meituan.net,REJECT
DOMAIN-SUFFIX,sankuai.com,REJECT
DOMAIN-SUFFIX,shifen.com,REJECT
DOMAIN-SUFFIX,tdnsv5.com,REJECT
DOMAIN-SUFFIX,wsdvs.com,REJECT

# 豪云社区微信小程序
URL-REGEX,^https?:\/\/.*adInf.*,REJECT
